### ISSUE TITLE
--no-readme confusion in the help text

### ISSUE THREAD

**Issue by junosuarez** [dominictarr/stability#2]
So, the help text:

```
stability STABILITY_LEVEL [options]
options:
-r, --readme    # add stability message to readme.
                # defaults to true unset with --no-readme
....
```

It's unclear what `--no-readme` does. I ran `stability stable` and `stability stable -d` a few times with no effect and was confused. Skimming through the code, I can't find anywhere where it's defaulting to this. Not sure what the intent was here.

**Comment by dominictarr** [comment]
I've changed the help message in https://github.com/dominictarr/stability/commit/294080928551bbf07c32f5c5a87950f532431e24
, is the meaning clearer?

Will change dry to not output if there is no change.

**Comment by junosuarez** [comment]
Seems clearer, but I don't notice it writing to the readme unless I explicitly call it with `-r`
